generator:
  class: sfPropelGenerator
  param:
    model_class:           invoicetype
    theme:                 vindjeplek
    non_verbose_templates: true
    with_show:             false
    singular:              invoicetype
    plural:                invoicetypes
    route_prefix:          invoicetype
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:  [title]
      filter:
        class:    false
      form:    ~
      edit:    ~
      new:     ~
