generator:
  class: sfPropelGenerator
  param:
    model_class:           propertyview
    theme:                 vindjeplek
    non_verbose_templates: true
    with_show:             false
    singular:              propertyview
    plural:                propertyviews
    route_prefix:          propertyview
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:  [title]
      filter:
        class:    false
      form:
        display:  [en<?php foreach(LanguagePeer::getIndex() as $oLang) { echo ','.$oLang->getCulture();} ?>]
      edit:    ~
      new:     ~
