generator:
  class: sfPropelGenerator
  param:
    model_class:           usertype
    theme:                 vindjeplek
    non_verbose_templates: true
    with_show:             false
    singular:              usertype
    plural:                usertypes
    route_prefix:          usertype
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:  [title]
      filter:
        class:    false
      form:
        display:  [title]
      edit:    ~
      new:     ~
