generator:
  class: sfPropelGenerator
  param:
    model_class:           page
    theme:                 vindjeplek
    non_verbose_templates: true
    with_show:             false
    singular:              page
    plural:                pages
    route_prefix:          page
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        custom_url: {label: "Alternate URL"}
      list:
        title: Pages
        display: [title, language, category, country]
        object_actions:
          comments: { label: "Comments", icon: "comments" }
          _edit:     ~
          _delete:   ~
      filter:
        display: [language_id, category_id, country_id, title]
      form:
        display:
          Relation:       [language_id, category_id, country_id]
          Content:        [intro, content]
          break:          [id]
          SEO:            [custom_url, meta_title, meta_description]
      edit:    ~
      new:     ~
